# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdinstance.example.io
spec:
  claimNames:
    kind: RDSInstance
    plural: rdsinstances
  group: example.io
  names:
    kind: XRDSInstance
    plural: xrdsinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: ObjectStorageSpec defines the desired state of ObjectStorage
              properties:
                resourceConfig:
                  description: All kind of RDS specific settings goes here.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: name of your RDS instance. It should be lowercase.
                      type: string
                    providerConfigName:
                      type: string
                    location:
                      enum:
                      - Mumbai
                      - Tokyo
                      type: string
                    diskSizeInGB:
                      type: integer
                    RAMSizeinGB: 
                      type: integer
                    diskSpeed: 
                      enum:
                      - slow
                      - moderate
                      - fast
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  - location
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              description: ObjectStorageStatus defines the observed state of ObjectStorage
              properties:
                bucketName:
                  type: string
                bucketArn:
                  type: string
              type: object
          type: object