apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: myapp-crossplane
  labels:
    testing.upbound.io/example-name: myapp-crossplane
spec:
  forProvider:
    region: ap-northeast-1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/subnet-type: private
    tags:
      Name: myapp-crossplane
