apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: myapp-crossplane-public-route
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane
    region: ap-northeast-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/routetable-type: public