apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    testing.upbound.io/example-name: myapp-crossplane-private-1a
  name: myapp-crossplane-private-1a
spec:
  forProvider:
    region: ap-northeast-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private-1a


---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    testing.upbound.io/example-name: myapp-crossplane-private-1b
  name: myapp-crossplane-private-1b
spec:
  forProvider:
    region: ap-northeast-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private-1b

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    testing.upbound.io/example-name: myapp-crossplane-private-1c
  name: myapp-crossplane-private-1c
spec:
  forProvider:
    region: ap-northeast-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: myapp-crossplane-private-1c 

