apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/securitygrouprule
  name: myapp-crossplane-web
spec:
  deletionPolicy: Delete
  forProvider:
    fromPort: 80
    protocol: tcp
    region: ap-northeast-1
    securityGroupIdSelector:
      matchLabels: 
        testing.upbound.io/example-name: myapp-crossplane-web
    self: true
    toPort: 80
    type: ingress 