apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    ami: ami-0d52744d6551d851e
    instanceType: t2.micro
    region: ap-northeast-1
