apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: myapp-crossplane
  labels:
      created-by: crossplane
      env: myapp-dev
      managed-by: crossplane
spec:
  forProvider:
    region: ap-northeast-1
    description: SecurityGroup
    vpcId: vpc-09f8b72a920c4ff34
    tags:
      created-by: crossplane
      env: myapp-dev
      managed-by: crossplane
  providerConfigRef:
    name: default
